[application]
name = "playground"
default_platform = "desktop"

[web.app]
title = "Inspector Playground"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[[desktop.window]]
title = "Profile Card"
width = 480
height = 640
resizable = true
